#!/bin/sh -e
# SPDX-License-Identifier: GPL-2.0-only
# Copyright (c) 2019 Max Rees
# See LICENSE for more information.

# af-arch BRANCH STARTDIR [STARTDIR...]
branch="$1"
shift
[ -n "$branch" ] || exit 1

af_getconf() {
	local file="$1"
	local key="$2"

	awk -v key="$key" '
		BEGIN { rc = 1 }
		$1 == key { $1 = ""; sub(/^ /, ""); print $0; rc = 0 }
		END { exit rc }' "$file"
}

af_checkarch() {
	local rc=1
	local i="$1"
	shift

	for j; do
		case "$j" in
		all | noarch)
			rc=0;;
		"$i")
			rc=0;;
		"!$i")
			rc=1
			break;;
		esac
	done

	return $rc
}

for startdir; do
	any=0
	repo="${startdir%/*}"

	APKBUILD="$startdir/APKBUILD"
	if ! [ -e "$APKBUILD" ]; then
		printf 'af-arch: %s: not found\n' "$APKBUILD" >&2
		exit 2
	fi

	archfile=".apkfoundry/$branch/arch"
	if ! [ -e "$archfile" ]; then
		printf 'af-arch: %s: not found\n' "$archfile" >&2
		exit 2
	fi

	arch="$(grep '^arch=' "$APKBUILD" \
		| sed "s/^arch=//; s/'//g; s/\"//g; s/#.*\$//")"

	unset -v override_commit
	if [ -e "$startdir/.af-arch" ]; then
		override_commit="$(cat "$startdir/.af-arch")"
	fi

	unset -v override_pkg
	if [ -e ".apkfoundry/$branch/arch-pkg" ]; then
		override_pkg="$(af_getconf ".apkfoundry/$branch/arch-pkg" "$startdir")" \
			|| unset -v override_pkg
	fi

	want_arches="$(af_getconf "$archfile" "$repo")" || true
	if [ -z "$want_arches" ]; then
		printf 'af-arch: warning: %s: repository not enabled\n' "$repo" >&2
		continue
	fi

	for i in $want_arches; do
		need_build=0
		if af_checkarch "$i" $arch; then
			need_build=1
		fi

		msg=""
		if [ -n "${override_pkg+x}" ] && ! af_checkarch "$i" $override_pkg; then
			msg="skipped by arch-pkg"
		elif [ -n "${override_commit+x}" ] && ! af_checkarch "$i" $override_commit; then
			msg="skipped by commit messages"
		fi

		if [ "$need_build" -eq 1 ]; then
			any=1
			[ -z "$msg" ] || printf '%s %s %s\n' "$i" "$startdir" "$msg" >&2
			printf '%s %s %s\n' "$i" "$startdir" "$msg"
		fi
	done
	if [ "$any" -eq 0 ]; then
		printf 'af-arch: warning: %s: not enabled on any arch\n' "$startdir" >&2
	fi
done
