#!/bin/sh -e
# SPDX-License-Identifier: GPL-2.0-only
# Copyright (c) 2019 Max Rees
# See LICENSE for more information.

# af-arch BRANCH STARTDIR [STARTDIR...]
branch="$1"
shift
[ -n "$branch" ] || exit 1

for startdir; do
	any=0
	repo="${startdir%/*}"

	APKBUILD="$startdir/APKBUILD"
	if ! [ -e "$APKBUILD" ]; then
		printf 'af-arch: %s: not found\n' "$APKBUILD" >&2
		exit 2
	fi

	archfile=".apkfoundry/$branch/arch"
	if ! [ -e "$archfile" ]; then
		printf 'af-arch: %s: not found\n' "$archfile" >&2
		exit 2
	fi

	arch="$(grep '^arch=' "$APKBUILD" \
		| sed "s/^arch=//; s/'//g; s/\"//g; s/#.*\$//")"

	want_arches="$(grep "^$repo " "$archfile" | cut -d ' ' -f 2-)"
	if [ -z "$want_arches" ]; then
		printf 'af-arch: warning: %s: repository not enabled\n' "$repo" >&2
		continue
	fi

	for i in $want_arches; do
		needs_build=0
		for j in $arch; do
			case "$j" in
			all | noarch)
				needs_build=1;;
			"$i")
				needs_build=1;;
			"!$i")
				needs_build=0
				break;;
			esac
		done

		if [ "$needs_build" -eq 1 ]; then
			any=1
			printf '%s %s\n' "$i" "$startdir"
		fi
	done
	if [ "$any" -eq 0 ]; then
		printf 'af-arch: warning: %s: not enabled on any arch\n' "$startdir" >&2
	fi
done
