#!/bin/sh -e
# SPDX-License-Identifier: GPL-2.0-only
# Copyright (c) 2019-2020 Max Rees
# See LICENSE for more information.
. /usr/share/abuild/functions.sh

list_has() {
	local needle="$1"
	local i
	shift
	for i in "$@"; do
		[ "$needle" = "$i" ] && return 0
		[ "$needle" = "!$i" ] && return 1
	done
	return 1
}

check_arch() {
	local ret=1
	local i
	for i in $arch; do
		case $i in
		all | noarch) ret=0 ;;
		"$CARCH") ret=0 ;;
		"!$CARCH") return 1 ;;
		esac
	done
	return $ret
}

while getopts s opt; do
case "$opt" in
s) skip_check=1;;
esac
done
shift "$((OPTIND - 1))"

for repo; do
for APKBUILD in "$repo"/*/APKBUILD; do
	[ -e "$APKBUILD" ] || continue

	pkgname=
	arch=
	options=
	depends_dev=
	depends=
	makedepends_build=
	makedepends_host=
	makedepends=
	checkdepends=
	subpackages=
	provides=
	. "$APKBUILD"
	startdir="${APKBUILD%/APKBUILD}"
	repo="${startdir%/*}"

	# If there isn't even a package name, let's move along
	[ -z "$pkgname" ] && continue

	[ -n "$skip_check" ] && checkdepends=
	list_has "!check" $options && checkdepends=

	if ! check_arch || list_has "!libc_$CLIBC" $options; then
		printf 'm %s .\n' "$startdir"
		continue
	fi

	for name in $pkgname $provides; do
		printf 'o %s %s\n' "${name%%[<>=~]*}" "$startdir"
	done
	for name in $subpackages; do
		printf 'o %s %s\n' "${name%%:*}" "$startdir"
	done

	for name in $depends $makedepends $checkdepends; do
		name="${name%%[<>=~]*}"
		case "$name" in
		"") continue;;
		"!"*) continue;;
		esac
		printf 'd %s %s\n' "$startdir" "$name"
	done
done
done
