#!/usr/bin/env python3
import logging   # basicConfig
import threading # Thread, current_thread

from apkfoundry.recv import recv, startup_flush
from apkfoundry.database import db_thread
from apkfoundry.dispatch import dispatch_thread
from apkfoundry.inbound import inbound_thread

threading.current_thread().name = "recv"

logging.basicConfig(
    level=logging.DEBUG,
    format="%(asctime)s %(levelname)s [%(threadName)s] %(message)s",
)

startup_flush()

threading.Thread(name="db", target=db_thread).start()
threading.Thread(name="mqtt", target=dispatch_thread).start()
threading.Thread(name="inbound", target=inbound_thread).start()

recv()
