#!/bin/sh -e
# SPDX-License-Identifier: GPL-2.0-only
# Copyright (c) 2019 Max Rees
# See LICENSE for more information.
scriptdir="${0%/*}"
. "$scriptdir/common"

for i; do
	if [ "${i%/APKBUILD}" = "$i" ]; then
		APKBUILDS="$APKBUILDS $i/APKBUILD"
	else
		APKBUILDS="$APKBUILDS $i"
	fi
done

# Add /dev/null so that we always get the filename prepended, even if only one
# APKBUILD is given
grep '^# Maintainer:' $APKBUILDS /dev/null \
	| sed -E 's@/APKBUILD:# Maintainer:\s*@ @' \
	| sort -uk1
