#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-only
# Copyright (c) 2019 Max Rees
# See LICENSE for more information.
import logging # basicConfig
import os      # getuid
import sys     # exit

from apkfoundry import get_config
from apkfoundry.root import listen

logging.basicConfig(
    level=logging.DEBUG,
    format="%(asctime)s %(levelname)s %(message)s",
)

rootid = get_config("chroot").getint("rootid")
if os.getuid() != _ROOTID:
    _LOGGER.critical(f"Must be run as user {rootid}")
    sys.exit(1)

listen()
