#!/bin/sh -e
# SPDX-License-Identifier: GPL-2.0-only
# Copyright (c) 2020 Max Rees
# See LICENSE for more information.
umask 007
builds_dir="$(mktemp -dp /var/lib/apkfoundry XXXXXXXXXX)"
chgrp apkfoundry "$builds_dir"

exec cat <<EOF
{
	"builds_dir": "$builds_dir",
	"builds_dir_is_shared": false,
	"driver": {
		"name": "apkfoundry",
		"version": "0.1"
	}
}
EOF
