#!/usr/bin/env python3
# vi:et
# SPDX-License-Identifier: GPL-2.0-only
# Copyright (c) 2020 Max Rees
# See LICENSE for more information.
import json       # dumps
import logging
import tempfile   # mkdtemp

import apkfoundry # LOCALSTATEDIR, VERSION
import apkfoundry._log as _log
import apkfoundry._util as _util

_log.init(color=True, sections=True)
env = _util.CI_Env()
apkfoundry.LOCALSTATEDIR.mkdir(parents=True, exist_ok=True)

builds_dir = tempfile.mkdtemp(
    dir=apkfoundry.LOCALSTATEDIR,
    prefix=f"gl-job-{env.job}-",
    suffix=".af"
)
logging.info("Container: %s", builds_dir)

print(json.dumps({
    "builds_dir": builds_dir,
    "builds_dir_is_shared": False,
    "driver": {
        "name": "apkfoundry",
        "version": apkfoundry.VERSION,
    },
}))
